#! /bin/bash

sbatch -psecondary-cs \
       --time=03:59:00 \
       --account=cs-sariel \
       --nodes=1 --mincpus=128 \
       --constraint=AE7713 \
       examples/scripts/run_all_tests_cluster
