#! /bin/bash

export JULIA_NUM_THREADS=auto

rm *.txt

find data/queries/sigspatial -type f > sigspatial.txt


start=`date +%s`
#e --track-allocation=user
julia \
    -O3 --min-optlevel=3 \
    examples/run_queries_test.jl sfile \
                             data/sigspatial/ \
                             sigspatial.txt
end=`date +%s`

runtime=$((end-start))
echo  "Running time: " $runtime
exit  -1;

# examples/run_queries_test.jl data/characters/
# data/tests/characters/characters_query_decider_10_0_plus.txt | gi
# undeci

