name: 'FrechetDist documentation'
description: 'Build and deploy the documentation for a Julia package.'
author: Sariel Har-Peled
on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg;\
                     Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - run: |
          julia --project=docs -e '
            using Documenter: doctest
            using FrechetDist
            doctest(FrechetDist)'
      - run: julia --project=docs docs/make.jl
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # For authentication with GitHub Actions token
        run: julia --project=docs/ docs/make.jl
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Julia 1.8.0
        uses: julia-actions/setup-julia@v1
        with:
          version: "1.8.0"
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v4-beta
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_